### ISSUE TITLE
grid-editing-excel-style sample does not show excel like editing.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-xplat-examples#121]
The sample at: https://github.com/IgniteUI/igniteui-xplat-examples/blob/master/samples/grids/grid/editing-excel-style.json
Which is here: https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/lob-grid/cell-editing#grid-excel-style-editing
Does not do excel-style like editing. 
You can compare with the angular one: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#grid-excel-style-editing
In it you can select a cell and directly start typing (like in excel). But in blazor the same does not work.

**Comment by mddifilippo89** [comment]
The sample works with the enter key as expected. It was based on this angular sample
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#grid-excel-style-editing
