### ISSUE TITLE
Grid Row reorder sample does not reorder.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-xplat-examples#125]
The sample at: https://github.com/IgniteUI/igniteui-xplat-examples/blob/master/samples/grids/grid/row-reorder.json
Which is here: https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/lob-grid/row-drag#row-reordering-demo

Does not allow reordering. You can drag the rows but on drop nothing happens.
It should behave like this sample: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#row-reordering-demo

**Comment by agoldenbaum** [comment]
Marking this closed. The sample is here: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/row-drag#row-reordering-demo and the row reordering is happening as expected.
