### ISSUE TITLE
[Blazor] Remove empty `OnInitialized` lifecycle method

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#159]
We can find many examples of Blazor code with an overridden `OnInitilized` lifecycle method, but many of those `OnInitialized` methods are empty.

We can find one of the examples in the document page for the `IgbAccordion` as below.
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/accordion

![image](https://user-images.githubusercontent.com/102948935/217187648-bc4202b1-947c-4e79-98af-99d5e26f6fe6.png)

Those empty `OnInitialized` methods should be removed from all of the Blazor example codes.

**Comment by HUSSAR-mtrela** [comment]
this issue should be fixed in the next build on staging
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/accordion
