### ISSUE TITLE
[Blazor] There is an injected `IIgniteUIBlazor` object in which never used.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#160]
We can find many examples of Blazor code with an injected `IIgniteUIBlazor` service object, but many of those injected `IIgniteUIBlazor` service objects are never used.

We can find one of the examples in the document page for the IgbAccordion as below.
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/accordion

![image](https://user-images.githubusercontent.com/102948935/217189815-4dbce204-12a5-45c2-b03a-4a80e1ab3b81.png)

Those unreferenced injections should be removed from all of the Blazor example codes.

**Comment by HUSSAR-mtrela** [comment]
fixed

**Comment by jsakamotoIGJP** [comment]
@HUSSAR-mtrela I really appreciate you fixing the problem! 

By the way, sorry for bothering you, but could you tell me the link to the commit you fixed the issue with?
