### ISSUE TITLE
[Blazor] I can't click the "COPY CODE" button when the browser screen is narrow.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#163]
Usually, the "COPY CODE" button on the example code window is really useful for me.

![image](https://user-images.githubusercontent.com/102948935/217445434-f63eff61-d803-45fb-81c3-78a1f58263c2.png)

However, when the browser window width is under 970 px, the "COPY CODE" button becomes unavailable to click because the button disappears when the mouse cursor is coming.

![movie-001](https://user-images.githubusercontent.com/102948935/217444491-1b20ef8d-9fb0-4e4d-adec-c89777a1ab5b.gif)

**Comment by HUSSAR-mtrela** [comment]
moved to https://github.com/IgniteUI/igniteui-docfx-template/issues/450
