### ISSUE TITLE
[Blazor] The warning CS1998 is caused

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#164]
We can find that many examples of Blazor code cause the warnings involved with a lack of awaiting codes in async methods (CS1998).

We can find one of the examples in the document page for the `IgbAccordion` as below.
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/layouts/accordion

![image](https://user-images.githubusercontent.com/102948935/217448555-d48d0916-643c-48a6-b8ca-a5022348f31c.png)

We should use the synchronous version of lifecycle methods when it doesn't contain any asynchronous operations. Therefore, we should change example codes like the below:

From:
```csharp
protected override async Task OnInitializedAsync()
{
    Categories.Add(new Category { Id = "0", Label = "Bike" });
    Categories.Add(new Category { Id = "1", Label = "Motorcycle" });
    ...
}
```

To:
```csharp
protected override void OnInitialized()
{
    Categories.Add(new Category { Id = "0", Label = "Bike" });
    Categories.Add(new Category { Id = "1", Label = "Motorcycle" });
    ...
}
```

**Comment by gmurray81** [comment]
I'm not considering this a high priority, more likely we will suppress. Oftentimes we are automatically emitting the handler, and it would be bothersome to discover whether or not it contained awaited things.

**Comment by HUSSAR-mtrela** [comment]
I suppressed warning CS1998 in project files

**Comment by jsakamotoIGJP** [comment]
@HUSSAR-mtrela The problem is the warning CS1998 will be generated by our customers copying and pasting the above sample code into their Blazor application project. Therefore, it makes no sense to suppress the warning CS1998 in our project file (.csproj) of the sample program. Please re-open this issue.

**Comment by gmurray81** [comment]
No, this is how we are fixing this one for now. We'd have to have the auto gen adjust which override was in use based on the contents and it's not worthwhile just to avoid this warning. Keep closed.

**Comment by jsakamotoIGJP** [comment]
Hi @gmurray81, Thank you for your comment! However, I'm a bit confused. I strongly agree with what you said below:

> Now this is ... and it's not worthwhile just to avoid this warning.

But you said:

> Keep closed.

I'm concerned that we could forget to improve this issue if we close issue #164 now. Is it too concerned me? 😅
