### ISSUE TITLE
[Blazor] Avoid the "async void" pattern

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#166]
We can find that the "async void" pattern is used in some of the example codes of Ignite UI for Blazor. For example, we can see the instance in the example code for the "IgbAcordion" below.

![image](https://user-images.githubusercontent.com/102948935/217733530-5f480749-8c7e-405f-a049-699ccbe4a2ee.png)

I sometimes see this "async void" pattern in the example codes for "Ignite UI for Blazor".

However, using the "async void" pattern is bad practice, especially applying it to event handler methods for the Razor component. If the handler method includes async operation, the changing states by that method might not cause re-rendering appropriately.

The method signature should be "async Task" if there is not enough reason to use the "async void".

```csharp
private async Task OnTimeClear()
{
    ...
```

**Comment by HUSSAR-mtrela** [comment]
fixed

**Comment by jsakamotoIGJP** [comment]
@HUSSAR-mtrela I really appreciate you fixing the problem! 

By the way, sorry for bothering you, but could you tell me the link to the commit you fixed the issue with?
