### ISSUE TITLE
[Blazor] Remove unuseful `Task.Delay` invoking

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-examples#167]
We can find the invoking `await Task.Delay(1)` in some of the example codes of Ignite UI for Blazor. For example, we can see the instance in the example code for the `IgbAcordion` below.

![image](https://user-images.githubusercontent.com/102948935/217735698-8efe558f-28c1-4c7c-bf6f-c709367a0283.png)

I sometimes see this invoking `await Task.Delay(1)` in the example codes for "Ignite UI for Blazor".

However, invoking `await Task.Delay(1)` must have no effect at all. So, that unnecessary invoking `await Task.Delay(1)` should be removed from all of the example codes on the Ignite UI for Blazor documents.

**Comment by HUSSAR-mtrela** [comment]
I removed Task.Delay(1) functions calls

**Comment by jsakamotoIGJP** [comment]
@HUSSAR-mtrela I really appreciate you fixing the problem! 

By the way, sorry for bothering you, but could you tell me the link to the commit you fixed the issue with?
