### ISSUE TITLE
[WC] Missing sample for Dock Manager 

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#174]
The styling sample for the WC Dock Manager is giving error message: 

Samples Browser is missing routing path:
/layouts/dock-manager-styling

Link: https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager#styling

![image](https://user-images.githubusercontent.com/52001020/222418987-c0ef0ef7-8f21-4939-aa73-1dcfb52bafff.png)

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager#styling
