### ISSUE TITLE
Components used in templates are not registered and don't show up

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-xplat-examples#176]
WC: https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/paging#web-components-grid-pagination-example
Blazor: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/paging#blazor-grid-pagination-example

![image](https://user-images.githubusercontent.com/3198469/224368564-767b4cf2-2059-4e07-a3a2-f7f5511e3d95.png)

Coming from 
https://github.com/IgniteUI/igniteui-xplat-examples/blob/8749c19909c9d063428655bcc7f29ef46bb3a345/samples/grids/grid/row-paging-basic.json#L45

that uses `<igc-linear-progress>` as a cell template, but in WC there's no call to `defineComponents(IgcLinearProgressComponent);` and for Blazor I'm not even quite sure what the recommended way to register would be. Perhaps including the module?

I'm assuming there are other possible scenarios like that, which is why I'm logging this as a more general issue.

In any case, if templates don't describe the components they use - they might need to?

**Comment by gmurray81** [comment]
@HUSSAR-mtrela 

please don't remove "unused" modules: https://github.com/IgniteUI/igniteui-xplat-examples/commit/8a5b4be8149622869cd57b7d4f1ee2c67dd5ae4c

**Comment by HUSSAR-mtrela** [comment]
this issues is fixed on production
