### ISSUE TITLE
Grid action strip sample shows "jump down" indicator in pinned rows but it appears to do nothing

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-examples#180]
goto https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/row-actions#custom-implementation

pin a couple rows using "pin" icon

hover over pinned row, click "jump down" indictor

nothing happens

**Comment by HUSSAR-mtrela** [comment]
@IGvaleries the "jump down" indictor works as expected. You just need to scroll away from pinned rows because "jump down" indictor will not do anything if pinned rows are already in the view.
