### ISSUE TITLE
Blazor Grid - row-reorder sample has no code to perform re-ordering

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-xplat-examples#182]
goto: https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/row-drag#row-reordering-demo

the help text states "Once [RowDraggable](https://www.infragistics.com/blazor/docs/api/api/IgniteUI.Blazor.Controls.IgbGridBaseDirective.html#IgniteUI_Blazor_Controls_IgbGridBaseDirective_RowDraggable) is enabled and a drop zone has been defined, you need to implement a simple handler for the drop event. When a row is dragged, check the following:"

but the sample does not implement does not handle any events

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/799
