### ISSUE TITLE
Grid should have more readable headers with spaces between words

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#186]
open any grid 
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/paging#blazor-grid-pagination-example

- headers show PropertyNames, e.g. "BeatsPerMinute" "TrackProgress"
- headers should show text with spaces e.g. "Beats Per Minute" "Track Progress"

![image](https://user-images.githubusercontent.com/11665978/228626322-fb59eb14-74d9-4d81-b48a-36cc8e9452ae.png)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-examples/pull/189
