### ISSUE TITLE
Broken template for binding-composite-data sample

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-xplat-examples#236]
There seems to be an additional `}` in the template. It should be removed
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/1182001/3348ca46-58ac-4941-b02a-19ee1e13c3f6)
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/data-grid#working-with-flat-data-example

**Comment by MayaKirova** [comment]
Resolved here: https://infragistics.visualstudio.com/NetAdvantage/_git/code-generation-library/pullrequest/9931
