### ISSUE TITLE
change y-axis location in toolbar samples 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#272]
open any of toolbar samples, e.g.
https://staging.infragistics.com/webcomponents-demos/samples/charts/toolbar/actions-built-in-category-chart
enable Values Labels - Show Last Value Label

Actual: the Final Value shows on left side while the last data point is on right side of the chart

Expected: in all [toolbar samples](ttps://github.com/IgniteUI/igniteui-xplat-examples/tree/23.1.x/samples/charts/toolbar)
change y-axis location to outside right 

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/6f9aafc5-d1b8-4bbc-8cb0-94a1a159918d)

**Comment by agoldenbaum** [comment]
Fixed
