### ISSUE TITLE
Chart Data Aggregation has more menu items than actual values

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#275]
open https://staging.infragistics.com/webcomponents-demos/samples/charts/category-chart/data-aggregations

expand Initial Summaries

observer that "as", "Sales" are listed as separate menu items instead of "Sum(Sales)"

Solution:
remove ALL "as Sales" strings from this line:
https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.1.x/samples/charts/category-chart/data-aggregations.json#L32C1-L32C1

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/f1590f57-0609-443b-a5e3-14611d2b776e)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-examples/pull/280
