### ISSUE TITLE
Editor for react add imports from web components when having property editor panel

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-examples#298]
When a sample has property editor panel it does generate imports from web components
```
import 'igniteui-webcomponents/themes/light/bootstrap.css';
import { defineAllComponents } from 'igniteui-webcomponents';

defineAllComponents();
```

This is observable here for example: https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.1.x/samples/grids/grid/multi-column-headers-overview.json

**Comment by gmurray81** [comment]
Prop editor is decoupled from the particular editors it uses. Possibly we could have one of the entry points define the WC though

**Comment by MayaKirova** [comment]
@gmurray81 Do you mean something like this: https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/10592 ? Or some other entry point?

**Comment by gmurray81** [comment]
Hmm... my concern is that including that define like that will probably pin all the WC stuff whenever the editor is included. We were doing defineAllComponents at the time because I think it was the only option. But if we were going to move the define to the constructor I think we should be more specific and just define the editors it needs (checkbox, dropdown (it should be using select instead, but that wasn't there yet), button, icon-button, input, slider)

**Comment by gmurray81** [comment]
I was really thinking of a specific module to register (see how we define modules for our other WC stuff) which registers the inputs and another one that doesn't.

My other concern would be nothing confuses the tree shaker into retaining the inputs if you include other stuff from igniteui-webcomponents-layouts without including editor (although, at this point most of the stuff in layouts uses igniteui-webcomponents)

**Comment by gmurray81** [comment]
we may even have an instance in which we have toolbar defining the WC stuff. Let me check.

**Comment by gmurray81** [comment]
a that's right, we didn't add a mode yet where toolbar uses the WC stuff for WC. maybe later.

Anyhow, it's just important that the tree shakers don't assume that importing the WC stuff is a side effect that always needs to be retained, o/w we are bloating apps that include stuff from layouts package. Keep in mind some of the entry points into our packages are a large flattened bundle that we rely on the tree shaker to trim to just the used pieces. With the latest tooling, maybe we should rethink if we still need these. I haven't check whether Angular still generates those for the APF
