### ISSUE TITLE
Editor for React generaes some weird component when having paginator

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-examples#299]
If you take a look at this sample: https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.1.x/samples/grids/grid/row-paging-options.json

See that the paginator has resourceStrings.
```
 "paginationComponents": [
        {
          "type": "WebPaginator",
          "name": "paginator",
          "perPage": 15,
          "displayDensity": "Cosy",
          "resourceStrings": {
            "type": "WebPaginatorResourceStrings",
            "igx_paginator_label": "Records per page"
          }
        }
      ],
```

I am not entirely sure what this is about but it generates as this
```
<IgrPaginatorResourceStrings
    igx_paginator_label="Records per page">
</IgrPaginatorResourceStrings>
```
and there is not a component like this

**Comment by MayaKirova** [comment]
Resolved but needs multiple PRs to come together:
https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/10595
https://infragistics.visualstudio.com/DefaultCollection/NetAdvantage/_git/dev-tools/pullRequest/10381
