### ISSUE TITLE
Editor for React. Using templates causes bad imports

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-examples#300]
When using templates from Web.ts sometimes there are imports for grid, event args and other. Those imports are transforming to 
`import { IgrRowDragEndEventArgs } from 'igniteui-react-grids/grids';` but should be transforming to 
`import { IgrRowDragEndEventArgs } from 'igniteui-react-grids';`

Observable here: https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.1.x/samples/grids/grid/row-reorder.json

**Comment by skrustev** [comment]
Seems to be already fixed in 23.2.x in PR 10567
