### ISSUE TITLE
Editor for React. Some samples generate with duplicate imports which throws error.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-xplat-examples#320]
For example conditional-cell-style-2: https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/grid/conditional-cell-style-2.json

It generates IgrGrid import twice:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/c3652416-d48f-4d61-a461-ccf063675e8a)

Which throws error: Identifier 'IgrGrid' has already been declared. (10:9)

Note: Maybe the code gen could try to prevent multiple imports or if not, since this probably comes from a event handlers or templates we can check for unnecessary imports like that.

**Comment by gmurray81** [comment]
I thought we already had code to avoid this. Will look. probably the duplicates are coming from a template/handler, but we are supposed to be parsing, and then merging these.

**Comment by dkamburov** [comment]
Yeah, I think this one is fixed already, forgot to close some of these issues
