### ISSUE TITLE
Row selection numbering demo does not load and throws error

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-xplat-examples#384]
If you look that the row selection numbering demo here: https://staging.infragistics.com/react-demos/grids/grid/row-selection-template-numbers you can see that it does not load and throws error in the console. If ran locally then it says it has something to do with the registration of the checkbox module

**Comment by mddragnev** [comment]
@dkamburov  This seems to be a product bug. If you look at any sample from the checkbox react topic you can see that the same error occurs. https://staging.infragistics.com/products/ignite-ui-react/react/components/inputs/checkbox here is the topic. @gmurray81 Could you please take a look at this? Also, should I log it somewhere else?

**Comment by gmurray81** [comment]
I believe I fixed this already, so we may just need a new beta. It had something to do with it trying to register the base class of checkbox. This used to be tolerated by igc-wc but no longer.

**Comment by mddragnev** [comment]
Yes this is already fixed with the latest beta9.
