### ISSUE TITLE
React Grid row dragging

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#395]
https://staging.infragistics.com/products/ignite-ui-react/react/components/grids/grid/row-drag#row-reordering-demo

When you drag a row to the bottom corner of the grid, second vertical sliders shows up

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/52001020/7ce6dd38-1353-416e-8f77-e044ba52c06f)

**Comment by dkamburov** [comment]
@radomirchev I can't reproduce this:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/1182001/25730380-bcc9-4748-ba38-b0dcddb448eb)

**Comment by skrustev** [comment]
This is not an issue, the element goes out of view so its natural for a scrollbar of the page to appear.
