### ISSUE TITLE
React Grid Row Pinning

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#396]
https://staging.infragistics.com/products/ignite-ui-react/react/components/grids/grid/row-pinning

On select of top/bottom row, no rows are pinned

**Comment by MayaKirova** [comment]
Already fixed in the product and there's an internal build with the fix: http://proget.infragistics.local:81/feeds/IgniteUI/@infragistics/igniteui-react-grids/23.2.468

There's no new public build yet but the fix will be included in the next public one as well.
