### ISSUE TITLE
Exported WC Grid Editing Events throws build error

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#400]
https://github.com/IgniteUI/igniteui-wc-examples/actions/runs/6577546253/job/17869423066#step:5:1943

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/39cd5fee-2f49-40b8-b339-f2b9e84f4499)

either there is a breaking change in WC Grid API or the event template needs changes
https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/code-gen-library/WebGridEditingEventsCellEdit/Web.ts#L14

**Comment by mddragnev** [comment]
This is fixed in the proget package @infragistics/igniteui-webcomponents-grids": "23.2.49"
