### ISSUE TITLE
Exported WC Grid Multi Column sample throws build error

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#402]
https://github.com/IgniteUI/igniteui-wc-examples/actions/runs/6577546253/job/17869423066#step:5:1983

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/19b0a82f-ce5a-41f8-9b38-2df2e23e209e)

**Comment by skrustev** [comment]
For some reason the IgcExporterEvent is translated to IgrExporterEventEventArgs and thus leading to confusion. I've logged it as a separate issue in NetAdvantage #27477 and for now just use React specific handler.
