### ISSUE TITLE
Broken WC TreeGrid keyboard-custom-navigation sample

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#438]
Auto-export PR failed checks:
https://github.com/IgniteUI/igniteui-wc-examples/pull/606

Errors in WC samples Build:
https://github.com/IgniteUI/igniteui-wc-examples/actions/runs/7134421663/job/19429192207?pr=606#step:5:1875

**Comment by MayaKirova** [comment]
That was bug in the product. It's already fixed, however the wc product build that the samples use does not include the fix yet. Not sure if we should wait for a new public version or if we can update the samples to use one of the dev builds(from proget). @dkamburov

**Comment by MayaKirova** [comment]
Closing since the PR now passes with the new updated product version: https://github.com/IgniteUI/igniteui-wc-examples/pull/606
