### ISSUE TITLE
disable transition in feature in some chart samples

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#470]
disable transition in feature in these chart samples:

- samples/charts/category-chart/highlighting
- samples/charts/category-chart/annotations
- samples/charts/category-chart/annotations-all
- samples/charts/category-chart/annotations-crosshairs
- samples/charts/category-chart/annotations-custom
- samples/charts/category-chart/annotations-final-value
- samples/charts/category-chart/annotations-callouts
- samples/charts/category-chart/tooltip-types

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-examples/pull/755
