### ISSUE TITLE
Chart YAxis max value is too small to see all series

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#471]
https://staging.infragistics.com/webcomponents-demos/samples/charts/data-chart/chart-highlight-filter-datasource

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/a70a9683-9982-44e8-a968-d05526562767)

**Comment by agoldenbaum** [comment]
Fixed by this PR: https://github.com/IgniteUI/igniteui-xplat-examples/pull/473
