### ISSUE TITLE
Excel style editing sample does not excel style edit

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-xplat-examples#538]
Sample at: https://staging.infragistics.com/products/ignite-ui-react/react/components/grids/grid/cell-editing#grid-excel-style-editing
Does not show excel style like editing. 
You should be able to click a cell and without enter edit mode start typing.

**Comment by skrustev** [comment]
This seems to be the same as #445

**Comment by MayaKirova** [comment]
Closing as duplicate of #445
