### ISSUE TITLE
Calendar Examples - WC, Blazor, React

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#616]
Calendar examples are not updated to the latest version of calendar component:

Angular Calendar:

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/52001020/385bdbbb-5689-4f51-8bf1-a6e25335209b)

WC, Blazor, React Calendar:

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/52001020/d52c6471-e28a-4c6a-a86d-09a044e3e40a)

**Comment by kacheshmarova** [comment]
In Angular documentation primary theme is material , however, React documentation uses bootstrap theme and I believe this is the reason for this issue being logged. React samples are actually using the latest version of the calendar. Having this in mind, I will close this issue.
