### ISSUE TITLE
Combo Example in React

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#618]
Combo Example for React is displaying the retired Combo component:

Link: https://www.infragistics.com/products/ignite-ui-react/react/components/editors/multi-column-combobox

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/52001020/d698b0a6-1bbb-449f-bf48-fd75ac945f7b)

**Comment by kacheshmarova** [comment]
This sample demonstrates Multi-Column Combo Box. For Combo Box sample and topics we have a different issue, which is  [1054](https://github.com/IgniteUI/igniteui-xplat-docs/issues/1054)
