### ISSUE TITLE
State Persistence Topic missing for WC, React, Blazor Tree and Hierarchical Grids

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-xplat-examples#668]
State Persistence feature is supported for WC, Blazor and React Tree and Hierarchical Grids but the documentation and samples are missing. Our clients can find out the feature is present only by chance!

**Comment by MayaKirova** [comment]
@radomirchev Note that the grid state persistence sample is custom sample. If we want the same type of sample for the other grids - with buttons, checkboxes, navigation between pages and so on, those will also need to be custom samples for WC/React/Blazor for each grid in the respective sample repos.

**Comment by radomirchev** [comment]
@MayaKirova noted :)
